spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/springboot
    username: ${db.id}
    password: ${db.pwd}

  config:
    import: key.yaml

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


management:
  endpoints:
    ## HTTP setting
    web:
      exposure:
        include: "*"
        exclude: "threaddump, heapdump"
      base-path: /act

    ## JMX setting
    jmx:
      exposure:
        include: "*"
        exclude: "threaddump, heapdump"

  ## End point Active
  endpoint:
    shutdown:
      enabled: true
    caches:
      enabled: false

## actuator info setting
